name: CML
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py 
          
          echo "# CML Report" >> report.md
          cat metrics.txt >> report.md
          cml comment create report.md
          
          
          
